# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

  #Replace these variables to suit your application
  projectName: 'SystemsService'
  websiteName: 'SystemsService'
  appPoolName: 'SystemsService'
stages:
- stage: DOTNET
  displayName: Build DOTNET
  jobs:
  - job: Build
    
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            dotnet build --configuration $(buildConfiguration)


