# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

  #Replace these variables to suit your application
  projectName: 'SystemsService'
  websiteName: 'SystemsService'
  appPoolName: 'SystemsService'
stages:
- stage: DOTNET
  displayName: Build DOTNET
  jobs:
  - job: Build
    
    steps:
      - task: CmdLine@2
        inputs:
          script: |
            dotnet build --configuration $(buildConfiguration)
- stage: 'Build'
  displayName: 'Build'
  jobs:
     - job: 
       steps:  
        # - task: DotNetCoreCLI@2
        #   displayName: 'dotnet restore'
        #   inputs:
        #     command: 'restore'
        #     projects: '*.sln'

        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: '*.sln'
            arguments: --configuration Release

        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: '*.sln'
            arguments: '--configuration $(BuildConfiguration)'
       
        - task: DotNetCoreCLI@2
          displayName: 'Publish the project - $(buildConfiguration)'
          inputs:
            command: 'publish'
            projects: '**/*.csproj'
            publishWebProjects: false
            arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
            zipAfterPublish: true

        - publish: '$(Build.ArtifactStagingDirectory)'
          artifact: drop


